/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;

import Modelo.Clientes;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author 36127512021.2
 */
public class TelaEmprestimo extends javax.swing.JFrame {

    /**
     * Creates new form TelaEmprestimo
     */
    public TelaEmprestimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        autor = new javax.swing.JTextField();
        titulo = new javax.swing.JTextField();
        codigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        cpf = new javax.swing.JTextField();
        fim = new javax.swing.JTextField();
        confirmar = new javax.swing.JButton();
        voltar = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        endereco = new javax.swing.JTextField();
        inicio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 153));
        jLabel1.setText("Emprestimo Livro");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(103, 11, 240, 30);

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 153));
        jLabel2.setText("Autor:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 60, 80, 21);

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 153));
        jLabel3.setText("Título:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 90, 80, 21);

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 153));
        jLabel4.setText("ISBN:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 120, 90, 21);
        getContentPane().add(autor);
        autor.setBounds(170, 60, 110, 20);

        titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloActionPerformed(evt);
            }
        });
        getContentPane().add(titulo);
        titulo.setBounds(170, 90, 110, 20);

        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });
        getContentPane().add(codigo);
        codigo.setBounds(170, 120, 110, 20);

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 153));
        jLabel5.setText("Nome:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 150, 80, 21);

        jLabel6.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 153));
        jLabel6.setText("Cpf:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 180, 60, 21);

        jLabel7.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 153));
        jLabel7.setText("Endereço:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 210, 110, 21);
        getContentPane().add(nome);
        nome.setBounds(170, 150, 110, 20);

        cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfActionPerformed(evt);
            }
        });
        getContentPane().add(cpf);
        cpf.setBounds(170, 180, 110, 20);

        fim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fimActionPerformed(evt);
            }
        });
        getContentPane().add(fim);
        fim.setBounds(170, 270, 110, 20);

        confirmar.setBackground(new java.awt.Color(153, 255, 153));
        confirmar.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        confirmar.setText("Confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });
        getContentPane().add(confirmar);
        confirmar.setBounds(220, 300, 130, 30);

        voltar.setBackground(new java.awt.Color(153, 255, 153));
        voltar.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(90, 300, 110, 31);

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 153));
        jLabel8.setText("Data de inicio:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 240, 150, 21);

        jLabel9.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 255, 153));
        jLabel9.setText("Data de Entrega:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 270, 160, 21);

        endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoActionPerformed(evt);
            }
        });
        getContentPane().add(endereco);
        endereco.setBounds(170, 210, 110, 20);

        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });
        getContentPane().add(inicio);
        inicio.setBounds(170, 240, 110, 20);

        jLabel10.setForeground(new java.awt.Color(153, 255, 153));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/abc.jpg"))); // NOI18N
        jLabel10.setText("jLabel3");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 400, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoActionPerformed

    private void tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloActionPerformed

    private void cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfActionPerformed

    private void fimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fimActionPerformed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        Clientes model = new Clientes();
        ExibeEmp EXI = new ExibeEmp(); 
        
        if ( (nome.getText().equals("")) && (autor.getText().equals("")) && (endereco.getText().equals("")) && (cpf.getText().equals(""))  && (codigo.getText().equals("")) && (titulo.getText().equals("")) ){
           JOptionPane.showMessageDialog(null, "NÃO PODE HAVER CAMPOS EM BRANCO!!!!\n"+
                                                "PREENCHA TODOS ELES !!!!");
            nome.setText("");
            endereco.setText("");
            autor.setText("");
            cpf.setText("");
            titulo.setText("");           
            codigo.setText("");
            setVisible(true);
        }
        else{
            

           //fazendo referencia aos metodos set do empregr
            
           model.setNome(nome.getText());
           model.setAutor(autor.getText());
           model.setEndereço(endereco.getText());
           model.setCpf(cpf.getText());
           model.setTitulo(titulo.getText());
           model.setInicio(inicio.getText());
           model.setFim(fim.getText());
           model.setCodigo(codigo.getText());
           
            EXI.exportarDados(model);
            EXI.setVisible(true);
           
       }
        
        
        
        try //tratamento de exceçãos
	   {
               
               String N = nome.getText();
               String A = autor.getText();
               String E = endereco.getText();
               String C = cpf.getText();
               String T = titulo.getText();
               String O = codigo.getText();
              
               
                String url = "jdbc:mysql://localhost/integradorlivro";
                
                String sql1 =  "DELETE FROM livro WHERE Titulo='"+T+"'";
                Connection conexao = DriverManager.getConnection(url, "root",""); //comando de conexão com banco
                PreparedStatement atualizar = conexao.prepareStatement(sql1);
                atualizar.executeUpdate();//método
                
                String url1 = "jdbc:mysql://localhost/integradorlivro";  
                String sql = "INSERT INTO cliente(Nome,Endereço,CPF,Titulo,codigo,autor) values ('"+N+"','"+E+"','"+A+"','"+C+"','"+T+"','"+O+"' )";

	     //Connection conexao = DriverManager.getConnection(url, "root",""); //comando de conexão com banco

	     //PreparedStatement atualizar = conexao.prepareStatement(sql);

	     atualizar.executeUpdate();//método

	     JOptionPane.showMessageDialog(null,"Cadastrado com sucesso!");
    
	   }
	  
	   catch(Exception erro) { 
           
              JOptionPane.showMessageDialog(null,"Erro na Conexão com Banco de Dados : "+erro);
               
           }
    }//GEN-LAST:event_confirmarActionPerformed

    private void enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoActionPerformed

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inicioActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        dispose();        
          
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField autor;
    private javax.swing.JTextField codigo;
    private javax.swing.JButton confirmar;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextField endereco;
    private javax.swing.JTextField fim;
    private javax.swing.JTextField inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField titulo;
    private javax.swing.JToggleButton voltar;
    // End of variables declaration//GEN-END:variables
}
