/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author 36127512021.2
 */
public class TelaPesquisa extends javax.swing.JFrame {

    /**
     * Creates new form TelaPesquisa
     */
    public TelaPesquisa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        pesquisar = new javax.swing.JButton();
        emprestimo = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 153));
        jLabel1.setText("Pesquisa de Livros");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 360, 43);

        titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloActionPerformed(evt);
            }
        });
        getContentPane().add(titulo);
        titulo.setBounds(20, 110, 210, 40);

        pesquisar.setBackground(new java.awt.Color(153, 255, 153));
        pesquisar.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        pesquisar.setText("Pesquisar");
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(pesquisar);
        pesquisar.setBounds(240, 110, 130, 40);

        emprestimo.setBackground(new java.awt.Color(153, 255, 153));
        emprestimo.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        emprestimo.setText("Fazer Empréstimo");
        emprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprestimoActionPerformed(evt);
            }
        });
        getContentPane().add(emprestimo);
        emprestimo.setBounds(90, 170, 210, 30);

        sair.setBackground(new java.awt.Color(153, 255, 153));
        sair.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        getContentPane().add(sair);
        sair.setBounds(50, 230, 110, 30);

        voltar.setBackground(new java.awt.Color(153, 255, 153));
        voltar.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(190, 230, 110, 31);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/abc.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 400, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloActionPerformed

        String url = "jdbc:mysql://localhost/integradorlivro";

        String sql = "SELECT * FROM livro WHERE Titulo = '"+titulo.getText()+"'";
        String Autor = null;
        String Titulo = null;
        String Codigo = null;
        String Editora = null;
        String Quantidade = null;
        
        try
        {

            Connection conexao = DriverManager.getConnection(url, "root","");

            PreparedStatement pesquisa = conexao.prepareStatement(sql);

            ResultSet resultado = pesquisa.executeQuery();

            while (resultado.next()) {

                Autor  = resultado.getString("Autor");
                Titulo = resultado.getString("Titulo");
                Codigo = resultado.getString("Codigo");
                Editora = resultado.getString("Editora");
                Quantidade = resultado.getString("Quantidade");

            }

            JOptionPane.showMessageDialog(null,"Dados encontrados com sucesso!\n"+
                "------------------------------\n"+
                "AUTOR  : "+Autor+"\n"+
                "TITULO : "+Titulo+"\n"+
                "CODIGO : "+Codigo+"\n"+
                "EDITORA : "+Editora+"\n"+
                "QUANTIDADE : "+Quantidade+"\n"+
                "------------------------------");

        }

        catch(Exception erro) {

            JOptionPane.showMessageDialog(null,"Erro na Conexão com Banco de Dados : "+erro);

        }
    
    }//GEN-LAST:event_tituloActionPerformed

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
        String A = null;
        String T = null;
        String E = null;
        String Q = null;
        String V = null;
        String I = null;

        try
        {

            String url = "jdbc:mysql://localhost/integradorlivro";

            Connection conexao = DriverManager.getConnection(url, "root","");

            String sql = "SELECT * FROM livro WHERE Titulo LIKE '%"+titulo.getText()+"%'";

            PreparedStatement pesquisa = conexao.prepareStatement(sql);

            ResultSet resultado = pesquisa.executeQuery();

            while (resultado.next()) {

                A  = resultado.getString("Autor");
                T = resultado.getString("Titulo");
                I = resultado.getString("ISBN");
                V = resultado.getString("Volume");
                Q = resultado.getString("Quantidade");
                 E = resultado.getString("Editora");

                JOptionPane.showMessageDialog(null,"Dados encontrados com sucesso!\n"+
                    "------------------------------\n"+
                "AUTOR  : "+A+"\n"+
                "TITULO : "+T+"\n"+
                "EDITORA : "+E+"\n"+
                "QUANTIDADE: "+Q+"\n"+
                "VOLUME : "+V+"\n"+
                "ISBN : "+I+"\n"+ 
                    "------------------------------");

            }

        }

        catch(Exception erro) {

            JOptionPane.showMessageDialog(null,"Erro na Conexão com Banco de Dados : "+erro);
        }
    }//GEN-LAST:event_pesquisarActionPerformed

    private void emprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprestimoActionPerformed
        TelaEmprestimo EMP = new TelaEmprestimo();
      
      EMP.setVisible(true);
    }//GEN-LAST:event_emprestimoActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        JOptionPane.showMessageDialog(null, "SEU PROGRAMA SERÁ ENCERRADO!");
        System. exit(0);        
                  
    }//GEN-LAST:event_sairActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPesquisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton emprestimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton pesquisar;
    private javax.swing.JButton sair;
    private javax.swing.JTextField titulo;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
